# Generated by Django 3.2.15 on 2022-09-19 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    DB_NAME = settings.DATABASES["default"]["NAME"]

    dependencies = [
        ("departments", "0005_auto_20210413_1702"),
    ]
    drop_tree_id_index_sql = f"""
    DROP INDEX {DB_NAME}.DEPARTMENTS_DEPARTMENT_TREE_ID_28CDC253
    """
    reverse_tree_id_index_sql = f"""
    CREATE INDEX DEPARTMENTS_DEPARTMENT_TREE_ID_28CDC253 ON {DB_NAME}.DEPARTMENTS_DEPARTMENT ("TREE_ID")
    """

    drop_parent_id_index_sql = f"""
    DROP INDEX {DB_NAME}.DEPARTMENTS_DEPARTMENT_PARENT_ID_CC8B848E
    """
    reverse_parent_id_index_sql = f"""
    CREATE INDEX DEPARTMENTS_DEPARTMENT_PARENT_ID_CC8B848E ON {DB_NAME}.DEPARTMENTS_DEPARTMENT ("PARENT_ID")
    """

    operations = [
        migrations.AlterIndexTogether(
            name="department",
            index_together={("parent_id", "tree_id", "lft"), ("tree_id", "lft", "rght")},
        ),
        migrations.RunSQL(
            sql=drop_tree_id_index_sql,
            reverse_sql=reverse_tree_id_index_sql,
        ),
        migrations.RunSQL(
            sql=drop_parent_id_index_sql,
            reverse_sql=reverse_parent_id_index_sql,
        ),
    ]
