# Generated by Django 3.2.15 on 2023-10-19 09:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0013_alter_profilecategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncprogresslog",
            name="failed_records"
        ),
        migrations.AddField(
            model_name='syncprogresslog',
            name='failed_records',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
